export interface Track {
  number: string;
  title: string;
  duration: string;
}

export interface Production {
  id: string;
  slug: string;
  title: string;
  client: string;
  category: 'corporate' | 'commercial' | 'music' | 'originals' | 'studio';
  subcategory?: string;
  director?: string;
  year?: string;
  thumbnail: string;
  description?: string;
  videoUrl?: string;
  images?: string[];
  genre?: string;
  status?: string;
  tracks?: Track[];
}

export const corporateProductions: Production[] = [
  {
    id: '1',
    slug: 'zto-vivatech',
    title: 'Discover your Potential',
    client: 'ZTO',
    category: 'corporate',
    subcategory: 'Employer Branding',
    thumbnail: 'https://ext.same-assets.com/3590549328/1668134854.jpeg',
    year: '2024',
  },
  {
    id: '2',
    slug: 'youtube-creative-economy',
    title: 'YouTube Creative Economy',
    client: 'YouTube',
    category: 'corporate',
    subcategory: 'Social Media',
    thumbnail: 'https://ext.same-assets.com/3590549328/4035039431.jpeg',
    year: '2024',
  },
  {
    id: '3',
    slug: 'malt-happy-new-work',
    title: 'Happy New Work',
    client: 'Malt',
    category: 'corporate',
    subcategory: 'Employer Branding',
    thumbnail: 'https://ext.same-assets.com/3590549328/281616622.jpeg',
    year: '2024',
  },
  {
    id: '4',
    slug: 'sephora',
    title: 'Youth to the people',
    client: 'Sephora',
    category: 'corporate',
    thumbnail: 'https://ext.same-assets.com/3590549328/54760505.jpeg',
    year: '2024',
  },
  {
    id: '5',
    slug: 'life-on-malt',
    title: 'Life On Malt',
    client: 'Malt',
    category: 'corporate',
    thumbnail: 'https://ext.same-assets.com/3590549328/4243170226.jpeg',
    year: '2024',
  },
  {
    id: '6',
    slug: 'augment',
    title: 'The MBA for Entrepreneurs',
    client: 'Augment',
    category: 'corporate',
    thumbnail: 'https://ext.same-assets.com/3590549328/547095939.jpeg',
    year: '2024',
  },
  {
    id: '7',
    slug: 'basf',
    title: 'Change Makers',
    client: 'BASF',
    category: 'corporate',
    thumbnail: 'https://ext.same-assets.com/3590549328/3664808754.jpeg',
    year: '2024',
  },
  {
    id: '8',
    slug: 'mentorshow',
    title: 'Learn From the Best',
    client: 'MentorShow',
    category: 'corporate',
    subcategory: 'Masterclasses',
    thumbnail: 'https://ext.same-assets.com/3590549328/396925950.jpeg',
    year: '2020 - 2025',
    description: 'Depuis 2020, FIRST FRAME accompagne Mentorshow, le leader européen des Masterclass en ligne, dans la production de toutes leurs formations exclusives. De la conception au tournage, en passant par la direction artistique et la post-production, nous mettons notre expertise audiovisuelle au service de contenus pédagogique et cinématographique.',
    images: [
      'https://ext.same-assets.com/3590549328/1369907080.jpeg',
      'https://ext.same-assets.com/3590549328/4075163797.jpeg',
      'https://ext.same-assets.com/3590549328/4181204235.jpeg',
      'https://ext.same-assets.com/3590549328/1945965050.jpeg',
      'https://ext.same-assets.com/3590549328/1169820240.jpeg',
      'https://ext.same-assets.com/3590549328/3453104023.jpeg',
    ],
  },
  {
    id: '9',
    slug: 'malt-x-axa-climate',
    title: 'Customer Testimony',
    client: 'Malt',
    category: 'corporate',
    subcategory: 'Customer Testimony',
    thumbnail: 'https://ext.same-assets.com/3590549328/655859879.png',
    year: '2024',
  },
  {
    id: '10',
    slug: 'make-up-for-ever',
    title: 'The Collective',
    client: 'Make Up For Ever',
    category: 'corporate',
    thumbnail: 'https://ext.same-assets.com/3590549328/3218417850.jpeg',
    year: '2024',
  },
  {
    id: '11',
    slug: 'ardian-sustainable-buyout',
    title: 'Sustainable Buyout',
    client: 'Ardian',
    category: 'corporate',
    thumbnail: 'https://ext.same-assets.com/3590549328/1217348596.jpeg',
    year: '2024',
  },
];

export const commercialProductions: Production[] = [
  {
    id: 'c1',
    slug: 'we-ward',
    title: 'The Walk',
    client: 'WeWard',
    category: 'commercial',
    subcategory: 'Brand Content',
    director: 'Matt Palmer',
    thumbnail: 'https://ext.same-assets.com/3590549328/3551640955.jpeg',
    year: '2024',
  },
  {
    id: 'c2',
    slug: 'vinted',
    title: "Léna's Dressing Room",
    client: 'Vinted',
    category: 'commercial',
    subcategory: 'TVC',
    director: 'Rafael Covo',
    thumbnail: 'https://ext.same-assets.com/3590549328/1655811988.jpeg',
    year: '2024',
  },
  {
    id: 'c3',
    slug: 'u-harry-potter',
    title: 'Wizarding World',
    client: 'Magasins U',
    category: 'commercial',
    director: 'Bastien Fiche',
    thumbnail: 'https://ext.same-assets.com/3590549328/2550148289.jpeg',
    year: '2024',
  },
  {
    id: 'c4',
    slug: 'deezer-premium',
    title: 'Your Music. Everywhere.',
    client: 'Deezer',
    category: 'commercial',
    director: 'Rafael Covo',
    thumbnail: 'https://ext.same-assets.com/3590549328/2111848467.jpeg',
    year: '2024',
  },
  {
    id: 'c5',
    slug: 'desperados-tropical',
    title: 'Desperados Tropical',
    client: 'Desperados',
    category: 'commercial',
    director: 'Antoine Hmono',
    thumbnail: 'https://ext.same-assets.com/3590549328/3524802415.jpeg',
    year: '2024',
  },
  {
    id: 'c6',
    slug: 'strava-segment-story',
    title: 'Segment Stories',
    client: 'STRAVA',
    category: 'commercial',
    director: 'Alexis Berg',
    thumbnail: 'https://ext.same-assets.com/3590549328/1587441237.jpeg',
    year: '2024',
  },
  {
    id: 'c7',
    slug: 'champion',
    title: 'True Champions',
    client: 'Champion',
    category: 'commercial',
    director: 'Emilio Boutros',
    thumbnail: 'https://ext.same-assets.com/3590549328/1552703511.jpeg',
    year: '2024',
  },
  {
    id: 'c8',
    slug: 'dim',
    title: 'DIM',
    client: 'DIM',
    category: 'commercial',
    director: 'Thomas Viard',
    thumbnail: 'https://ext.same-assets.com/3590549328/1508702670.jpeg',
    year: '2024',
  },
  {
    id: 'c9',
    slug: 'ellesfontyoutube',
    title: 'They Make YouTube',
    client: 'YouTube',
    category: 'commercial',
    director: 'Las Favoritas',
    thumbnail: 'https://ext.same-assets.com/3590549328/1292478365.jpeg',
    year: '2024',
  },
  {
    id: 'c10',
    slug: 'qonto-bigger-desk',
    title: 'Bigger Desk',
    client: 'Qonto',
    category: 'commercial',
    director: 'Thierry Le Mer',
    thumbnail: 'https://ext.same-assets.com/3590549328/2301445922.jpeg',
    year: '2024',
  },
  {
    id: 'c11',
    slug: 'karmine-corp-vgc',
    title: 'Roster Reveal',
    client: 'Karmine Corp',
    category: 'commercial',
    director: 'Bastien Fiche',
    thumbnail: 'https://ext.same-assets.com/3590549328/3806159209.jpeg',
    year: '2024',
  },
  {
    id: 'c12',
    slug: 'marionnaud-kcp-love',
    title: "L'art d'Offrir",
    client: 'Marionnaud',
    category: 'commercial',
    director: 'Nathan Cahen',
    thumbnail: 'https://ext.same-assets.com/3590549328/2068152421.jpeg',
    year: '2024',
  },
];

export const musicProductions: Production[] = [
  {
    id: 'm1',
    slug: 'musique-documentaire-esport',
    title: 'Level Up - OST',
    client: 'First Frame',
    category: 'music',
    subcategory: 'Documentary',
    director: 'Axel Covo',
    thumbnail: 'https://ext.same-assets.com/3590549328/4280035452.jpeg',
    year: '2024',
    tracks: [
      { number: '01', title: 'Main Theme', duration: '3:24' },
      { number: '02', title: 'Rise Up', duration: '2:45' },
      { number: '03', title: 'Digital Dreams', duration: '4:12' },
      { number: '04', title: 'Competition', duration: '3:08' },
      { number: '05', title: 'Victory Lane', duration: '2:56' },
      { number: '06', title: 'End Credits', duration: '4:30' },
    ],
  },
  {
    id: 'm2',
    slug: 'musique-immersive-documentaire-echecs',
    title: 'Inside the Mind of a Genius - OST',
    client: 'CLICHE',
    category: 'music',
    subcategory: 'Documentary',
    director: 'Axel Covo',
    thumbnail: 'https://ext.same-assets.com/3590549328/186996560.jpeg',
    year: '2024',
    tracks: [
      { number: '01', title: 'Opening Gambit', duration: '3:15' },
      { number: '02', title: 'The Mind Palace', duration: '4:22' },
      { number: '03', title: 'Chess Meditation', duration: '5:00' },
      { number: '04', title: 'Checkmate', duration: '3:45' },
    ],
  },
  {
    id: 'm3',
    slug: 'musique-documentaire-cyclisme',
    title: "Le Temps d'un Weekend - OST",
    client: 'RAYON PROD x QUAD',
    category: 'music',
    subcategory: 'Documentary',
    director: 'Axel Covo',
    thumbnail: 'https://ext.same-assets.com/3590549328/2000347708.jpeg',
    year: '2024',
    tracks: [
      { number: '01', title: 'Départ', duration: '2:30' },
      { number: '02', title: 'La Montée', duration: '4:15' },
      { number: '03', title: 'Peloton', duration: '3:45' },
      { number: '04', title: 'Sprint Final', duration: '2:58' },
      { number: '05', title: 'Victoire', duration: '3:20' },
    ],
  },
  {
    id: 'm4',
    slug: 'de-coeur-et-dor-ost',
    title: "De Coeur et d'Or - OST",
    client: 'QUAD LAB',
    category: 'music',
    subcategory: 'Documentary',
    director: 'Axel Covo et Charles Sicouri',
    thumbnail: 'https://ext.same-assets.com/3590549328/2881539012.jpeg',
    year: '2024',
    tracks: [
      { number: '01', title: 'GOLDEN HEART', duration: '3:33' },
      { number: '02', title: 'THE TEAM', duration: '1:50' },
      { number: '03', title: 'LOCK DOWN SYNDROM', duration: '1:59' },
      { number: '04', title: 'TRAINING DAY', duration: '1:51' },
      { number: '05', title: 'BACK TO BUSINESS', duration: '2:26' },
      { number: '06', title: 'OUR DNA', duration: '2:08' },
      { number: '07', title: 'FLOOD & BLOOD', duration: '1:47' },
      { number: '08', title: 'TO THE TOP', duration: '1:45' },
      { number: '09', title: 'DEFEATED', duration: '0:48' },
      { number: '10', title: 'END STATEMENT', duration: '0:45' },
      { number: '11', title: 'DERBY', duration: '2:02' },
      { number: '12', title: 'BACK TO THE FIGHT', duration: '0:49' },
      { number: '13', title: 'STREET LIFE', duration: '1:08' },
      { number: '14', title: 'FAMILY TIME', duration: '2:22' },
      { number: '15', title: 'THE COACH', duration: '2:01' },
      { number: '16', title: 'MUM AND DAD', duration: '3:25' },
      { number: '17', title: 'YOUTH TEAM', duration: '1:13' },
      { number: '18', title: 'BEFORE THE MATCH', duration: '1:29' },
      { number: '19', title: 'ALL IT TAKES', duration: '1:21' },
      { number: '20', title: 'ON THE ROAD', duration: '1:00' },
      { number: '21', title: 'SCHOOL TIME', duration: '2:25' },
      { number: '22', title: 'FUN IN TOWN', duration: '0:35' },
      { number: '23', title: 'BIG GAME', duration: '1:36' },
      { number: '24', title: 'MORE SWEAT', duration: '0:54' },
      { number: '25', title: 'BROKEN DREAMS', duration: '1:08' },
      { number: '26', title: 'LIFE AFTER ALL', duration: '3:37' },
      { number: '27', title: 'GOAL EMOTION', duration: '1:50' },
      { number: '28', title: 'THE MESSAGE', duration: '1:48' },
    ],
  },
  {
    id: 'm5',
    slug: 'dior',
    title: 'Dior - OST',
    client: 'QUAD LAB',
    category: 'music',
    director: 'Axel Covo & Charles Sicouri',
    thumbnail: 'https://ext.same-assets.com/3590549328/645472900.jpeg',
    year: '2024',
    tracks: [
      { number: '01', title: 'Elegance', duration: '3:00' },
      { number: '02', title: 'Haute Couture', duration: '2:45' },
      { number: '03', title: 'Paris Nights', duration: '4:20' },
    ],
  },
  {
    id: 'm6',
    slug: 'lens-de-sang-et-dor-ost',
    title: "Lens, De Sang et d'Or - OST",
    client: 'ELIDE x QUAD',
    category: 'music',
    director: 'Axel Covo',
    thumbnail: 'https://ext.same-assets.com/3590549328/3676375351.jpeg',
    year: '2024',
    tracks: [
      { number: '01', title: 'Sang et Or', duration: '3:12' },
      { number: '02', title: 'La Passion', duration: '4:05' },
      { number: '03', title: 'Stade Bollaert', duration: '3:30' },
      { number: '04', title: 'Hymne Final', duration: '4:00' },
    ],
  },
];

export const originalsProductions: Production[] = [
  {
    id: 'o1',
    slug: 'tess-ledeux',
    title: 'TESS LEDEUX',
    client: 'First Frame',
    category: 'originals',
    genre: 'Documentary',
    status: 'Released',
    thumbnail: 'https://ext.same-assets.com/3590549328/3551640955.jpeg',
    year: '2024',
    description: 'An intimate portrait of freestyle skiing champion Tess Ledeux, following her journey to Olympic glory.',
  },
  {
    id: 'o2',
    slug: 'the-roots-of-to-your-eternity',
    title: 'The Roots of To Your Eternity',
    client: 'First Frame',
    category: 'originals',
    genre: 'Documentary',
    status: 'Released',
    thumbnail: 'https://ext.same-assets.com/3590549328/1655811988.jpeg',
    year: '2024',
    description: 'A deep dive into the creation of the beloved anime series To Your Eternity.',
  },
  {
    id: 'o3',
    slug: 'anime',
    title: 'ANIME',
    client: 'First Frame',
    category: 'originals',
    genre: 'Documentary',
    status: 'In Production',
    thumbnail: 'https://ext.same-assets.com/3590549328/2111848467.jpeg',
    year: '2025',
    description: 'Exploring the cultural phenomenon of Japanese animation and its global impact.',
  },
  {
    id: 'o4',
    slug: 'level-up',
    title: 'Level Up',
    client: 'First Frame',
    category: 'originals',
    genre: 'Documentary',
    status: 'Released',
    thumbnail: 'https://ext.same-assets.com/3590549328/4280035452.jpeg',
    year: '2024',
    description: 'The rise of esports and competitive gaming culture around the world.',
  },
];

export const studioProductions: Production[] = [
  {
    id: 's1',
    slug: 'tess-main-title',
    title: 'TESS Main Title',
    client: 'First Frame',
    category: 'studio',
    subcategory: 'Title Design',
    thumbnail: 'https://ext.same-assets.com/3590549328/3551640955.jpeg',
    year: '2024',
  },
  {
    id: 's2',
    slug: 'anime-main-title',
    title: 'ANIME Main Title',
    client: 'First Frame',
    category: 'studio',
    subcategory: 'Title Design',
    thumbnail: 'https://ext.same-assets.com/3590549328/2111848467.jpeg',
    year: '2024',
  },
  {
    id: 's3',
    slug: 'studio-reel-2023',
    title: 'Studio Reel 2023',
    client: 'First Frame',
    category: 'studio',
    subcategory: 'Showreel',
    thumbnail: 'https://ext.same-assets.com/3590549328/1552703511.jpeg',
    year: '2023',
  },
  {
    id: 's4',
    slug: 'trade-republic',
    title: 'Trade Republic',
    client: 'Trade Republic',
    category: 'studio',
    subcategory: 'Motion Design',
    thumbnail: 'https://ext.same-assets.com/3590549328/547095939.jpeg',
    year: '2024',
  },
  {
    id: 's5',
    slug: 'malt-studio',
    title: 'Malt',
    client: 'Malt',
    category: 'studio',
    subcategory: 'Motion Design',
    thumbnail: 'https://ext.same-assets.com/3590549328/281616622.jpeg',
    year: '2024',
  },
  {
    id: 's6',
    slug: 'dynamo',
    title: 'Dynamo',
    client: 'Dynamo',
    category: 'studio',
    subcategory: '3D Animation',
    thumbnail: 'https://ext.same-assets.com/3590549328/3664808754.jpeg',
    year: '2024',
  },
  {
    id: 's7',
    slug: 'nft-sneakers',
    title: 'NFT Sneakers',
    client: 'Various',
    category: 'studio',
    subcategory: '3D Animation',
    thumbnail: 'https://ext.same-assets.com/3590549328/3218417850.jpeg',
    year: '2023',
  },
  {
    id: 's8',
    slug: 'youtube-graphics',
    title: 'YouTube Graphics',
    client: 'YouTube',
    category: 'studio',
    subcategory: 'Motion Design',
    thumbnail: 'https://ext.same-assets.com/3590549328/4035039431.jpeg',
    year: '2024',
  },
];

export const heroSlides = [
  {
    id: 1,
    title: 'THE WALK',
    client: 'Matt Palmer',
    year: '2024',
    videoUrl: 'https://ext.same-assets.com/3590549328/3953287438.mp4',
    thumbnail: 'https://ext.same-assets.com/3590549328/3551640955.jpeg',
  },
  {
    id: 2,
    title: 'VINTED',
    client: 'Rafael Covo',
    year: '2024',
    thumbnail: 'https://ext.same-assets.com/3590549328/1655811988.jpeg',
  },
  {
    id: 3,
    title: 'DEEZER',
    client: 'Rafael Covo',
    year: '2024',
    thumbnail: 'https://ext.same-assets.com/3590549328/2111848467.jpeg',
  },
  {
    id: 4,
    title: 'CHAMPION',
    client: 'Emilio Boutros',
    year: '2024',
    thumbnail: 'https://ext.same-assets.com/3590549328/1552703511.jpeg',
  },
  {
    id: 5,
    title: 'DESPERADOS',
    client: 'Antoine Hmono',
    year: '2024',
    thumbnail: 'https://ext.same-assets.com/3590549328/3524802415.jpeg',
  },
  {
    id: 6,
    title: 'STRAVA',
    client: 'Alexis Berg',
    year: '2024',
    thumbnail: 'https://ext.same-assets.com/3590549328/1587441237.jpeg',
  },
];

export const navLinks = [
  { label: 'Advertisement', href: '/productions/commercial' },
  { label: 'Originals', href: '/productions/originals' },
  { label: 'Corporate', href: '/productions/corporate' },
  { label: 'Music', href: '/productions/music' },
  { label: 'Studio', href: '/productions/studio' },
];

export const clientLogos = [
  { name: 'Sephora', image: 'https://ext.same-assets.com/3590549328/2022478860.png' },
  { name: "L'Oreal", image: 'https://ext.same-assets.com/3590549328/255048582.png' },
  { name: 'Renault', image: 'https://ext.same-assets.com/3590549328/1195403245.png' },
  { name: 'Netflix', image: 'https://ext.same-assets.com/3590549328/3079206555.png' },
  { name: 'France TV', image: 'https://ext.same-assets.com/3590549328/1487596826.png' },
  { name: 'DIM', image: 'https://ext.same-assets.com/3590549328/2517788466.png' },
  { name: 'Harley Davidson', image: 'https://ext.same-assets.com/3590549328/3341671849.png' },
  { name: 'Google', image: 'https://ext.same-assets.com/3590549328/2440011035.png' },
];

export const services = [
  {
    number: '01',
    title: 'CONCEPTION',
    items: [
      'Creative strategy & ideation',
      'Scriptwriting & storytelling',
      'Art direction & mood boards',
      'Storyboarding & pre-visualization',
    ],
  },
  {
    number: '02',
    title: 'PRODUCTION',
    items: [
      'Scouting, casting, scripting & logistics',
      'Studio & on-location video & Photo shoots',
      'Set design, lighting, sound',
    ],
  },
  {
    number: '03',
    title: 'POST-PRODUCTION',
    items: ['Editing', 'Color grading', 'VFX', 'Final mastering & delivery'],
  },
  {
    number: '04',
    title: 'STUDIO',
    items: ['Art Direction', '2D / 3D Motion Design', 'Title design'],
  },
  {
    number: '05',
    title: 'SOUND',
    items: ['Film scoring', 'Sound-Design', 'Mix & Mastering', 'Voice-over recording'],
  },
];

export const corporateFilters = [
  { label: 'All', value: 'all' },
  { label: 'Employer Branding', value: 'employer-branding' },
  { label: 'Masterclasses', value: 'masterclass' },
  { label: 'Social Media', value: 'production' },
  { label: 'Motion Design', value: 'motiondesign' },
  { label: 'Customer Testimony', value: 'customer-testimony' },
];

export const commercialFilters = [
  { label: 'All', value: 'all' },
  { label: 'Brand Content', value: 'brand-content' },
  { label: 'Social Media', value: 'social-media' },
  { label: 'TVC', value: 'tvc' },
];

export const originalsFilters = [
  { label: 'All', value: 'all' },
  { label: 'Documentary', value: 'documentary' },
  { label: 'Fiction', value: 'fiction' },
];

export const originalsStatusFilters = [
  { label: 'All', value: 'all' },
  { label: 'Released', value: 'released' },
  { label: 'In Production', value: 'in-production' },
];

export const studioFilters = [
  { label: 'All', value: 'all' },
  { label: 'Title Design', value: 'title-design' },
  { label: 'Motion Design', value: 'motion-design' },
  { label: '3D Animation', value: '3d-animation' },
  { label: 'Showreel', value: 'showreel' },
];
